name: pytest

on: [push]

jobs: 
    name: pytest-and-mypy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install .
        python -m stg.install
    - name: Test with pytest
      run: |
        pip install coverage
        pip install pytest-cov
        pip install pytest
        pytest
    - name: Static type checking
      run: |
        pip install mypy
        mypy
