name: pytest

on: [push]

jobs:
  job1:
    name: test-coverage-mypy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip    
          pip install -U pip        
          pip install .
      - name: Test with pytest
        run: |
          pip install coverage==4.5.4
          pip install pytest-cov        
          pip install pytest
          pytest
      - name: Submit coverage report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALL_SECRET }}
        run: |
          pip install coveralls
          coveralls
      - name: Static type checking
        run: |
          pip install mypy==1.0.1
          mypy
